[package]
name = "vanityhash"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
secp256k1 = { version = "0.27.0", features = ["rand"] }
bech32 = "0.9.1"
hex = "0.4.3"
sha2 = "0.10.6"
itertools = "0.11.0"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
